import QtQuick
import qs.Commons
import qs.Ui

Column {
  id: root
  required property var service
  required property var requestConfirmation
  width: parent ? parent.width : implicitWidth
  spacing: Style.space(12)

  readonly property string credentialState: service ? String(service.duckCredentialState || "") : ""
  readonly property bool connected: credentialState === "connected" || credentialState === "available" || credentialState === "ready"
  readonly property bool configured: connected || credentialState === "attention"

  PanelSectionHeader { text: "DUCKDUCKGO EMAIL PROTECTION" }

  StatusBanner {
    reserveSpace: true
    text: root.service && root.service.duckError
      ? String(root.service.duckError)
      : root.connected
        ? "DuckDuckGo Email Protection connected."
        : "Connect a bearer token to create private Duck addresses."
    error: root.service && root.service.duckError !== ""
  }

  Column {
    visible: !root.connected
    width: parent.width
    spacing: Style.space(8)

    Text {
      width: parent.width
      text: "Open setup, sign in, then open DevTools Network. Generate a private address and copy the Authorization value after Bearer."
      color: Color.muted
      font.family: Style.font.family
      font.pixelSize: Style.font.bodySmall
      wrapMode: Text.WordWrap
    }
    Button {
      text: "Open Setup"
      iconText: ""
      focusable: true
      onClicked: root.service.openUrl("https://duckduckgo.com/email")
    }
    TextField {
      id: tokenField
      width: parent.width
      placeholderText: "Bearer token"
      password: true
      onAccepted: connect()
      function connect() {
        var value = text
        if (!value) return
        root.service.connectProvider("duckduckgo", value)
        clear()
      }
    }
    Button {
      text: "Connect DuckDuckGo"
      iconText: "󰌘"
      focusable: true
      enabled: tokenField.text.length > 0 && !root.service.actionBusy
      onClicked: tokenField.connect()
    }
  }

  Column {
    visible: root.configured
    width: parent.width
    spacing: Style.space(10)

    Button {
      readonly property bool generating: root.service.duckOperation === "generate"
      width: Style.space(142)
      text: !root.service.duckRemoteAvailable ? "Try Again"
        : generating ? "Generating..." : "Create Alias"
      iconText: generating ? "󰦖" : (!root.service.duckRemoteAvailable ? "󰑓" : "+")
      iconSpinning: generating
      focusable: true
      enabled: root.connected && !root.service.actionBusy
      onClicked: {
        if (!root.service.duckRemoteAvailable) root.service.retryDuckRequests()
        root.service.generateDuck()
      }
    }

    PanelSeparator {}
    PanelSectionHeader { text: "KNOWN DUCK ALIASES" }

    Text {
      visible: !root.service.knownDuckAliases || root.service.knownDuckAliases.length === 0
      width: parent.width
      text: "No aliases generated by this plugin yet."
      color: Color.muted
      font.family: Style.font.family
      font.pixelSize: Style.font.body
      horizontalAlignment: Text.AlignHCenter
    }

    Repeater {
      model: root.service.knownDuckAliases || []
      delegate: AddressHistoryCard {
        required property var modelData
        readonly property bool activeAlias: modelData.active === true
        readonly property bool refreshing: root.service.duckOperation === "status"
          && root.service.duckTargetAddress === address
        readonly property bool updating: root.service.duckOperation === "setActive"
          && root.service.duckTargetAddress === address
        providerLabel: "DuckDuckGo"
        address: String(modelData.address || "")
        statusText: activeAlias ? "Active" : "Inactive"
        statusColor: activeAlias ? Color.accent : Color.muted
        actions: [
          {
            id: "refresh",
            width: Style.space(116),
            text: refreshing ? "Refreshing..." : "Refresh",
            icon: refreshing ? "󰦖" : "󰑓",
            busy: refreshing,
            enabled: root.connected && !root.service.actionBusy
          },
          {
            id: "toggle",
            width: Style.space(132),
            text: updating ? "Updating..." : (activeAlias ? "Deactivate" : "Reactivate"),
            icon: updating ? "󰦖" : "",
            busy: updating,
            destructive: activeAlias,
            enabled: root.connected && root.service.duckRemoteAvailable && !root.service.actionBusy
          }
        ]
        onCopyRequested: root.service.copyText(address)
        onForgetRequested: root.requestConfirmation(
          "Forget " + address + " from this plugin?",
          function() { root.service.forgetDuck(address) },
          "Forget")
        onActionRequested: function(actionId) {
          if (actionId === "refresh") {
            root.service.refreshDuck(address)
          } else if (!activeAlias) {
            root.service.setDuckActive(address, true)
          } else {
            root.requestConfirmation(
              "Deactivate " + address + "? It will stop forwarding messages.",
              function() { root.service.setDuckActive(address, false) },
              "Deactivate")
          }
        }
      }
    }

    PanelSeparator {}
    Button {
      text: "Disconnect DuckDuckGo"
      iconText: "󰌙"
      focusable: true
      enabled: !root.service.actionBusy
      foreground: Color.urgent
      onClicked: root.requestConfirmation(
        "Disconnect DuckDuckGo and remove its saved token? Known aliases will be forgotten locally.",
        function() { root.service.disconnectProvider("duckduckgo") },
        "Disconnect")
    }
  }
}
