import QtQuick
import QtQuick.Layouts
import qs.Commons
import qs.Ui

ColumnLayout {
  id: root
  required property var service
  required property var requestConfirmation

  width: parent ? parent.width : implicitWidth
  height: parent ? parent.height : implicitHeight
  spacing: Style.space(12)

  readonly property string credentialState: service ? String(service.duckCredentialState || "") : ""
  readonly property bool connected: credentialState === "connected" || credentialState === "available" || credentialState === "ready"
  readonly property bool configured: connected || credentialState === "attention"
  readonly property bool fullPanelHeight: root.configured

  PanelSectionHeader {
    Layout.fillWidth: true
    text: "DUCKDUCKGO EMAIL PROTECTION"
  }

  StatusBanner {
    Layout.fillWidth: true
    reserveSpace: true
    text: root.service && root.service.duckError
      ? String(root.service.duckError)
      : root.connected
        ? "DuckDuckGo Email Protection connected."
        : "Connect a bearer token to create private Duck addresses."
    error: root.service && root.service.duckError !== ""
  }

  ColumnLayout {
    visible: !root.connected
    Layout.fillWidth: true
    spacing: Style.space(8)

    Text {
      Layout.fillWidth: true
      text: "Open setup, sign in, then open DevTools Network. Generate a private address and copy the Authorization value after Bearer."
      color: Color.muted
      font.family: Style.font.family
      font.pixelSize: Style.font.bodySmall
      wrapMode: Text.WordWrap
    }

    Button {
      text: "Open Setup"
      iconText: ""
      focusable: true
      onClicked: root.service.openUrl("https://duckduckgo.com/email")
    }

    TextField {
      id: tokenField
      Layout.fillWidth: true
      placeholderText: "Bearer token"
      password: true
      onAccepted: connect()
      function connect() {
        var value = text
        if (!value) return
        root.service.connectProvider("duckduckgo", value)
        clear()
      }
    }

    Button {
      text: "Connect DuckDuckGo"
      iconText: "󰌘"
      focusable: true
      enabled: tokenField.text.length > 0 && !root.service.actionBusy
      onClicked: tokenField.connect()
    }
  }

  ColumnLayout {
    visible: root.configured
    Layout.fillWidth: true
    Layout.fillHeight: true
    Layout.minimumHeight: 0
    spacing: Style.space(10)

    Button {
      readonly property bool generating: root.service.duckOperation === "generate"
      width: Style.space(142)
      text: !root.service.duckRemoteAvailable ? "Try Again"
        : generating ? "Generating..." : "Create Alias"
      iconText: generating ? "󰦖" : (!root.service.duckRemoteAvailable ? "󰑓" : "+")
      iconSpinning: generating
      focusable: true
      enabled: root.connected && !root.service.actionBusy
      onClicked: {
        if (!root.service.duckRemoteAvailable) root.service.retryDuckRequests()
        root.service.generateDuck()
      }
    }

    ScrollableHistory {
      Layout.fillWidth: true
      Layout.fillHeight: true
      Layout.minimumHeight: 0
      title: "KNOWN DUCK ALIASES"
      emptyText: "No aliases generated by this plugin yet."
      model: root.service.knownDuckAliases || []
      delegateComponent: Component {
        AddressHistoryCard {
          required property var modelData
          width: ListView.view ? ListView.view.width : implicitWidth
          readonly property bool activeAlias: modelData.active === true
          readonly property bool refreshing: root.service.duckOperation === "status"
            && root.service.duckTargetAddress === address
          readonly property bool updating: root.service.duckOperation === "setActive"
            && root.service.duckTargetAddress === address
          providerLabel: "DuckDuckGo"
          address: String(modelData.address || "")
          statusText: activeAlias ? "Active" : "Inactive"
          statusColor: activeAlias ? Color.accent : Color.muted
          actions: [
            {
              id: "refresh",
              width: Style.space(116),
              text: refreshing ? "Refreshing..." : "Refresh",
              icon: refreshing ? "󰦖" : "󰑓",
              busy: refreshing,
              enabled: root.connected && !root.service.actionBusy
            },
            {
              id: "toggle",
              width: Style.space(132),
              text: updating ? "Updating..." : (activeAlias ? "Deactivate" : "Reactivate"),
              icon: updating ? "󰦖" : "",
              busy: updating,
              destructive: activeAlias,
              enabled: root.connected && root.service.duckRemoteAvailable && !root.service.actionBusy
            }
          ]
          onCopyRequested: root.service.copyText(address)
          onForgetRequested: root.requestConfirmation(
            "Forget " + address + " from this plugin?",
            function() { root.service.forgetDuck(address) },
            "Forget")
          onActionRequested: function(actionId) {
            if (actionId === "refresh") {
              root.service.refreshDuck(address)
            } else if (!activeAlias) {
              root.service.setDuckActive(address, true)
            } else {
              root.requestConfirmation(
                "Deactivate " + address + "? It will stop forwarding messages.",
                function() { root.service.setDuckActive(address, false) },
                "Deactivate")
            }
          }
        }
      }
    }

    PanelSeparator {
      Layout.fillWidth: true
    }

    Button {
      text: "Disconnect DuckDuckGo"
      iconText: "󰌙"
      focusable: true
      enabled: !root.service.actionBusy
      foreground: Color.urgent
      onClicked: root.requestConfirmation(
        "Disconnect DuckDuckGo and remove its saved token? Known aliases will be forgotten locally.",
        function() { root.service.disconnectProvider("duckduckgo") },
        "Disconnect")
    }
  }
}
