import QtQuick
import qs.Commons
import qs.Ui

Column {
  id: root
  required property var service
  required property var requestConfirmation
  width: parent ? parent.width : implicitWidth
  spacing: Style.space(12)

  readonly property string credentialState: service ? String(service.duckCredentialState || "") : ""
  readonly property bool connected: credentialState === "connected" || credentialState === "available" || credentialState === "ready"
  readonly property bool configured: connected || credentialState === "attention"

  PanelSectionHeader { text: "DUCKDUCKGO EMAIL PROTECTION" }

  StatusBanner {
    text: "Unofficial integration. DuckDuckGo may change or disable the API without notice."
    warning: true
  }

  StatusBanner {
    text: root.service && root.service.duckError ? String(root.service.duckError) : ""
    error: true
  }

  Row {
    visible: root.service && root.service.duckBusy
    spacing: Style.space(8)
    Text { text: "󰦖"; color: Color.foreground; font.family: Style.font.family; font.pixelSize: Style.font.icon
      RotationAnimator on rotation { from: 0; to: 360; duration: 800; loops: Animation.Infinite; running: parent.visible }
    }
    Text { text: "Working..."; color: Color.muted; font.family: Style.font.family; font.pixelSize: Style.font.body }
  }

  Column {
    visible: !root.connected
    width: parent.width
    spacing: Style.space(8)

    Text {
      width: parent.width
      text: "Open setup, sign in, then open DevTools Network. Generate a private address and copy the Authorization value after Bearer."
      color: Color.muted
      font.family: Style.font.family
      font.pixelSize: Style.font.bodySmall
      wrapMode: Text.WordWrap
    }
    Button {
      text: "Open Setup"
      iconText: ""
      focusable: true
      onClicked: root.service.openUrl("https://duckduckgo.com/email")
    }
    TextField {
      id: tokenField
      width: parent.width
      placeholderText: "Bearer token"
      password: true
      onAccepted: connect()
      function connect() {
        var value = text
        if (!value) return
        root.service.connectProvider("duckduckgo", value)
        clear()
      }
    }
    Button {
      text: "Connect DuckDuckGo"
      iconText: "󰌘"
      focusable: true
      enabled: tokenField.text.length > 0 && !root.service.actionBusy
      onClicked: tokenField.connect()
    }
  }

  Column {
    visible: root.configured
    width: parent.width
    spacing: Style.space(10)

    Button {
      text: "Quick Generate"
      iconText: "+"
      focusable: true
      enabled: root.connected && root.service.duckRemoteAvailable && !root.service.duckBusy
      onClicked: root.service.generateDuck()
    }

    Button {
      visible: root.connected && !root.service.duckRemoteAvailable
      text: "Try Again"
      iconText: "󰑓"
      focusable: true
      enabled: !root.service.duckBusy
      onClicked: root.service.retryDuckRequests()
    }

    PanelSeparator {}
    PanelSectionHeader { text: "KNOWN DUCK ALIASES" }

    Text {
      visible: !root.service.knownDuckAliases || root.service.knownDuckAliases.length === 0
      width: parent.width
      text: "No aliases generated by this plugin yet."
      color: Color.muted
      font.family: Style.font.family
      font.pixelSize: Style.font.body
      horizontalAlignment: Text.AlignHCenter
    }

    Repeater {
      model: root.service.knownDuckAliases || []
      delegate: Rectangle {
        required property var modelData
        width: root.width
        implicitHeight: duckRow.implicitHeight + Style.space(16)
        radius: Style.cornerRadius
        color: Util.alpha(Color.foreground, 0.05)
        readonly property string address: String(modelData.address || "")
        readonly property bool activeAlias: modelData.active === true
        readonly property string status: activeAlias ? "Active" : "Inactive"

        Column {
          id: duckRow
          anchors.left: parent.left
          anchors.right: parent.right
          anchors.verticalCenter: parent.verticalCenter
          anchors.margins: Style.space(8)
          spacing: Style.space(6)

          Row {
            width: parent.width
            Text { width: parent.width - statusText.width - Style.space(8); text: address; color: Color.foreground; font.family: Style.font.family; font.pixelSize: Style.font.body; font.bold: true; elide: Text.ElideMiddle }
            Text { id: statusText; text: status; color: activeAlias ? Color.accent : Color.muted; font.family: Style.font.family; font.pixelSize: Style.font.caption }
          }
          Row {
            spacing: Style.space(4)
            Button { text: "Copy"; focusable: true; onClicked: root.service.copyText(address) }
            Button { text: "Refresh"; focusable: true; enabled: root.connected && !root.service.duckBusy; onClicked: root.service.refreshDuck(address) }
            Button {
              text: activeAlias ? "Deactivate" : "Reactivate"
              focusable: true
              foreground: activeAlias ? Color.urgent : Color.foreground
              enabled: root.connected && root.service.duckRemoteAvailable && !root.service.duckBusy
              onClicked: {
                if (!activeAlias) root.service.setDuckActive(address, true)
                else root.requestConfirmation("Deactivate " + address + "? It will stop forwarding messages.", function() { root.service.setDuckActive(address, false) }, "Deactivate")
              }
            }
            Button { text: "Forget"; focusable: true; foreground: Color.urgent; onClicked: root.requestConfirmation("Forget " + address + " from this plugin?", function() { root.service.forgetDuck(address) }, "Forget") }
          }
        }
      }
    }

    PanelSeparator {}
    Button {
      text: "Disconnect DuckDuckGo"
      iconText: "󰌙"
      focusable: true
      enabled: !root.service.actionBusy
      foreground: Color.urgent
      onClicked: root.requestConfirmation(
        "Disconnect DuckDuckGo and remove its saved token? Known aliases will be forgotten locally.",
        function() { root.service.disconnectProvider("duckduckgo") },
        "Disconnect")
    }
  }
}
